[package]
name = "pumpkin-macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
serde.workspace = true
itertools.workspace = true

proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
serde_json = "1.0.132"
